# Generated by Django 4.2 on 2023-05-06 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_usercustomer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usercustomer',
        ),
    ]
